### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by hadisfr** [graphia-app/graphia#13]
Hi
I randomly ended up monitoring my memory usage (with `htop`) while using Graphia.
It seems that whenever Graphia takes memory to open a large graph, etc. it won't release the resources until the whole process terminated. I opened a large graphml file and then closed the tab. My memory usage stayed on 14GB and Graphia was using about 80% of systems memory.
I'm suspicious to some kind of memory leak . It may cause serious performance problems. Please take a look. 🤔 
P.S. I'm using Graphia 2.2 on Linux Ubuntu.

**Comment by timangus** [comment]
It's pretty unlikely to be a memory leak tbh, but it might look that way. Graphia typically allocates memory with a high watermark type strategy, only deallocating when the document (or the whole application) is closed. This is partly how it manages to perform well on large graphs; it avoids frequent memory management. The other thing to point out is that the memory is allocated almost entirely via smart pointers, which by design do not leak.

Also, be wary of interpreting the output of top/htop etc.. Depending on specifically which figures you're looking at, they can be misleading (e.g. including cached pages etc.).

If you really feel there is a specific memory leak present, feel free to reopen.
