### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by iggisv9t** [graphia-app/graphia#2]
```
>>>./Graphia.AppImage
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

[1]    2930 abort (core dumped)  ./Graphia.AppImage
```
Platform: Archlinux x64
I tried to install libxcb as google suggested, but it did not help me. Now trying to build it from source, but it's not successful without build instructions.

**Comment by iggisv9t** [comment]
```❯ ./linuxdeployqt-6-x86_64.AppImage
linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
still-supported mainstream distribution, which currently is glibc 2.20.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
```
Ok, build from source is harder then I thought. `/installers/linux/build.sh` prompted that it failed to find linuxdeployqt, so I tried to install it, but it seems like there is no simple way for my system.

**Comment by timangus** [comment]
Looks like you might have run into this issue: https://github.com/AppImage/AppImageUpdate/issues/85

Binary distribution on linux is hard :(

As for building, newer versions of linuxdeployqt are basically impossible to use on a modern system. This is a conscious decision by its author to force people to use it on very old systems and thus maxmise binary compatibility of the resultant binaries. The binaries we distribute were built on a newer system using an older version of linuxdeployqt, essentially because using old systems is substantially more work and maintenance overhead. If we see a lot of failures then we might revisit this, but for "mainstream" Linux distros things should work OK.

I have updated the README to include some basic build instructions though. You won't get an AppImage (that's what installers/linux/build.sh is for), but you should still get an executable binary. I think this is probably the best you can hope for with Arch, for now.

**Comment by iggisv9t** [comment]
For me the right qt prefix path was `CMAKE_PREFIX_PATH=/usr/lib/cmake/Qt5/`. Now it just works and I should say works very well.

**Comment by timangus** [comment]
Cool, glad to hear you got it working. For what it's worth setting CMAKE_PREFIX_PATH should only be necessary in the case where you have manually installed Qt from their website. In the case that the system installed Qt is configured and recent enough, it shouldn't be necessary to set the environment variable at all. 👍
