### ISSUE TITLE
unable to load attributes from external table 

### ISSUE THREAD

**Issue by IvanSterligov** [graphia-app/graphia#45]
Hello and thanks for the wonderful app, it handles large datasets much better than cyto or gephi :) Very good for bibliometrics.

However, I'm having trouble with adding node attributes. I'm building a coauthorship network from a simple pairs csv file which looks like:

author,another
10038769200,7004189995
10038769200,57216132820
10038769200,57234470700
10038769200,7004189995

and I'm trying to add author names to nodes via a helper table:

auid,name
6602795575,John
24476298500,Jack
23060890300,Nina
9839269600,Alex
36962018000,Mike

the problem is Graphia is unable to detect keys in the helper file. In the dropdown menu in the import wizard there is only one column "name" available as a key. Strangely, the second column auid, which I intend to use as node keys, turns up on the next step as a column with data to load. 

Tried csv, excel, adding various other columns - still no success, the column with ids is always absent from the key selection screen. Why so? Maybe I'm doing something not right?

**Comment by timangus** [comment]
(Apologies for the slow reply.) It seems you've run into a slightly obscure bug whereby the types of a data columns are detected in order to determine if they're suitable to be used as keys, that is to say whether they are integers or strings. In your case, the numbers are relatively large, and the test that considers if they're integers fails since it only considers integers that can be encoded in 32 bits. I've now fixed this in 471a74cc.

You could try and see if this fixes your problem: https://graphia.dev/?dir=Latest . Alternatively if you want to stick with the version you have a workaround would be to simply make your ids strings instead of integers, so e.g. instead of "6602795575", you could use "id6602795575".
