### ISSUE TITLE
GML import produces "unspecified error"

### ISSUE THREAD

**Issue by JamesEarlOwens** [graphia-app/graphia#75]
I get an error upon attempting to open my GML files. This happens with either Generic or Websearch plugin selected. Do GMLs  need to be formatted in an unusual way?  My GML files open in GEPHI and are standard formatting. 
Error: [filename].gml could not be opened due to an unspecified error.
Thanks for your help and insights.

**Comment by timangus** [comment]
Could you supply the file that's failing? Or if it's sensitive data some other example that doesn't work?

**Comment by JamesEarlOwens** [comment]
Sure. Here is a GML file that loads in GEPHI but not in Graphia. I changed the extension to TXT to make it attach. THANK YOU!
[TEST_all_ngrams_network.gml.txt](https://github.com/graphia-app/graphia/files/14764811/TEST_all_ngrams_network.gml.txt)

**Comment by timangus** [comment]
The problem appears to be that the id numbers used in the file violate the [GML standard](https://github.com/GunterMueller/UNI_PASSAU_FMI_Graph_Drawing/blob/master/GML/gml-technical-report.pdf) in two ways:

- Many of them are negative
- Most (all?) of them exceed 32 bits

> Integers
> GML uses signed 32-bit integers, which are commonly available on all architectures and languages. Larger numbers
> should be represented as strings. Especially, bitsets with more than 31 entries should be represented as strings.

Strictly speaking Gephi is wrong to accept and parse this file. Graphia's error message is woeful though; I need to improve parsing error messages in general. To solve your issue I suggest that you adjust whatever is generating the file so that the numbers adhere to the above.
